# Copyright (c) 2024 Thiago Alves
# SPDX-License-Identifier: MIT

# This file is a partial configuration for the Keymap Drawer CLI that will parse
# my keyboard configurations, and generate layout map images that are as close
# as they can get to what I mannually created when this whole configration
# stater.
#
# The goal of this file is to be diff betweem the full configuration and one
# that does not have any "shift" values showing on keys. You can use this file
# to update the full configuration, and you should have a valid config.

parse_config:
  zmk_keycode_map:
    # Keyboard & Keypad: Keyboard → Numbers
    #---------------------------------------------------------------------------
    # I need to define the numbers mapping because we need to override the
    # default value that has all the symbols on the shift position.
    NUMBER_1: "1"
    N1: "1"
    NUMBER_2: "2"
    N2: "2"
    NUMBER_3: "3"
    N3: "3"
    NUMBER_4: "4"
    N4: "4"
    NUMBER_5: "5"
    N5: "5"
    NUMBER_6: "6"
    N6: "6"
    NUMBER_7: "7"
    N7: "7"
    NUMBER_8: "8"
    N8: "8"
    NUMBER_9: "9"
    N9: "9"
    NUMBER_0: "0"
    N0: "0"

    # Keyboard & Keypad: Keyboard → Symbols / Punctuation
    EQUAL: "="
    MINUS: "-"
    SLASH: "/"
    FSLH: "/"
    BACKSLASH: '\'
    BSLH: '\'
    NON_US_BACKSLASH: '\'
    NON_US_BSLH: '\'
    NUBS: '\'
    SEMICOLON: ";"
    SEMI: ";"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    COMMA: ","
    PERIOD: "."
    DOT: "."
    LEFT_BRACKET: "["
    LBKT: "["
    RIGHT_BRACKET: "]"
    RBKT: "]"
    GRAVE: "`"
