---
include:
  - keyboard: Corne 42 nice!view
    board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DEXTRA_CONF_FILE=../../config/corne_niceview.conf
    artifact-name: zmk-corne-42-niceview-left
    # shield: corne_left nice_view_adapter nice_view
  - keyboard: Corne 42 nice!view
    board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    cmake-args: -DEXTRA_CONF_FILE=../../config/corne_niceview.conf
    artifact-name: zmk-corne-42-niceview-right
    # shield: corne_right nice_view_adapter nice_view
  - keyboard: Corne 42 nice!view
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-corne-42-niceview-settings-reset
